name: release
on:
  push:
    tags:
      - "v*"
  release:
    types:
      - published
  workflow_call:
    inputs:
      release_tag:
        type: string
        required: true
      
permissions:
  contents: write

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_VERSION: "8.0.x"
  
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - uses: cli/gh-extension-precompile@v2
        with:
          build_script_override: script/build.sh
          release_tag: ${{ inputs.release_tag || github.ref }}
          
