version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      nuget-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      nuget-production:
        dependency-type: production
        update-types:
          - patch
