name: Test

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_VERSION: "8.0.x"
  GH_TOKEN: ${{ github.token }}

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install gh extension
        run: gh extension install .
      - name: Install template
        run: gh csharp-template install
      - name: Create new project
        run: |
          mkdir -p gh-csharp-extension-test
          cd gh-csharp-extension-test
          gh csharp-template new
      - name: Build new project
        working-directory: gh-csharp-extension-test
        run: script/build.sh
      - name: list dist
        working-directory: gh-csharp-extension-test
        shell: pwsh
        run: Get-ChildItem -Path dist
