name: Test

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  GH_TOKEN: ${{ github.token }}

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        dotnet-version:
          - "8.0"
          - "9.0"
    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install gh extension
        run: gh extension install .
      - name: Install template
        run: gh csharp-template install
      - name: Create new project
        run: |
          mkdir -p gh-csharp-extension-test
          cd gh-csharp-extension-test
          gh csharp-template new -- --DotNetVersion ${{ matrix.dotnet-version }}
      - name: Build new project
        working-directory: gh-csharp-extension-test
        shell: bash
        run: script/build.sh
      - name: list dist
        working-directory: gh-csharp-extension-test
        shell: pwsh
        run: Get-ChildItem -Path dist
      - name: Install development gh extension
        working-directory: gh-csharp-extension-test
        run: gh extension install .
      - name: Run gh development command
        working-directory: gh-csharp-extension-test
        run: gh csharp-extension-test
